### ISSUE TITLE
Apache FPM Jail option

### ISSUE THREAD

**Issue by Nirjonadda** [AnoopAlias/nDeploy#260] opened 2017-08-08 09:35 UTC
Please add enable/disable option for Apache FPM Jail without remove the file /var/cpanel/feature_toggles/apachefpmjail? Its not good idea to removeing files for fixing the problem.

**Comment by AnoopAlias** [comment] 2017-08-08 09:39
This is not a bug. The toggle file is a blank file.the presence of which determine the state of chroot.
Closing this

**Closed as completed by AnoopAlias** 2017-08-08 09:39 UTC

**Comment by Nirjonadda** [comment] 2017-08-08 09:53
So this files apachefpmjail have lot of problem and Unable to Connect to STMP server. Only deleting files is fix ?

**Comment by AnoopAlias** [comment] 2017-08-08 10:03
https://forums.cpanel.net/threads/php-fpm-chrooted-to-virtfs.596787/

This is a security feature and chroots php-fpm pool .But as mentioned sometimes due to bug in cPanel implementation ,name resolution etc has problem in the chroot. This is mostly fixed if you do
su - username
Or if you disable chroot by removing the apachefpmjail  file.
