### ISSUE TITLE
nginx worker processes segfaulting

### ISSUE THREAD

**Issue by dotsam** [AnoopAlias/nDeploy#68] opened 2016-02-15 23:57 UTC
Running the latest version of nDeploy on a 64 bit CentOS 7 server, I'm getting the nginx worker processes segfaulting fairly frequently. This is on a server with only a single test site with just me loading pages. This happens on the stock CentOS 7 kernel as well as a GRsec enabled kernel. Any thoughts where to start looking?

From /var/log/nginx/error.log:
```
2016/02/15 18:49:51 [notice] 9582#9582: signal process started
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8054 exited on signal 11
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8147 exited on signal 11
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8049 exited on signal 11
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8051 exited on signal 11
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8082 exited on signal 11
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8194 exited on signal 11
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8050 exited on signal 11
2016/02/15 18:49:53 [alert] 1487#1487: worker process 8052 exited on signal 11
```

And from syslog:
```
Feb 15 18:49:53  kernel: nginx[8194]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel: nginx[8052]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
Feb 15 18:49:53  kernel: nginx[8049]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
Feb 15 18:49:53  kernel: nginx[8051]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
Feb 15 18:49:53  kernel: nginx[8054]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
Feb 15 18:49:53  kernel: nginx[8147]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
Feb 15 18:49:53  kernel: nginx[8050]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
Feb 15 18:49:53  kernel: nginx[8082]: segfault at 0 ip 00000000004a5d9b sp 00007ffc36362738 error 4
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
Feb 15 18:49:53  kernel:  in nginx[400000+b97000]
```

**Comment by AnoopAlias** [comment] 2016-02-16 00:13
@dotsam - Please see https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#

You can build your own binary on your cpanel server by running

```
git clone https://github.com/AnoopAlias/nDeploy.git
cd nDeploy/rpm_buildtree/
./nDeploy-nginx_build_script.centos7.sh

```
The script tries to rsync the binary over to rpm.piserve.com which you can ignore. The rpm will be present in cd nDeploy/rpm_buildtree/nginx-pkg-64-centos7

Which you can rpm -ivh

**Comment by AnoopAlias** [comment] 2016-02-16 01:54
This should most probably be something wrong in your os setup as the same binary works fine in many servers without issue and this is the first case of segfault reported.

Let me know if you were able to nail it down

**Comment by AnoopAlias** [comment] 2016-02-16 22:34
@dotsam - Were you able to find the cause?.

**Comment by dotsam** [comment] 2016-02-16 23:32
The process that's segfaulting isn't doing a core dump for some reason, and the debug logs haven't been very revealing as of yet. Oddly enough, the segfaults never seem to result in any failed connections that I can see, but none the less, I don't like processes just segfaulting. I'm going to try and simplify down my configuration (currently wordpress fastcgi/php-fpm/ssl/ipv6) and see if I can narrow it down that way.

**Comment by dotsam** [comment] 2016-02-17 01:15
So I have this narrowed down a little. The segfault happens when nginx reloads its configuration when it receives a SIGHUP signal. I can send the signal myself, but there's also something causing nginx to reload itself (not sure about the internal workings of nginx, so I can't say if this is normal or not).

If I rebuild nginx without pagespeed, then the segfault doesn't occur under the same conditions. If I change the version of pagespeed to 1.9.32.10 (which is tagged as the "latest" release in the pagespeed repo) then things are also fine. So somewhere in these [151 commits](https://github.com/pagespeed/ngx_pagespeed/compare/v1.9.32.10-beta...master) is the change that's causing my segfault. I'm going to keep digging in to this a little more tomorrow.

**Comment by AnoopAlias** [comment] 2016-02-17 02:05
FYI  as per https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source

We should be doing pagespeed 1.10.33.4 which is what nDeploy build script use

**Comment by dotsam** [comment] 2016-02-17 02:12
Finally got core dumps working correctly, tracked it down to the shutdown procedure in pagespeed, and I've filed a bug with them https://github.com/pagespeed/ngx_pagespeed/issues/1120

**Comment by AnoopAlias** [comment] 2016-02-17 02:15
k cool

**Comment by dotsam** [comment] 2016-02-17 17:52
The bug in ngx_pagespeed has been fixed. This was happening when the pagespeed module was compiled in, but had no config. I expect that this may actually be the case for a number of nDeploy users, but as it wasn't actually impacting anything but the workers as they shut down, nobody noticed. It's fixed in the latest 1.10.33.5 release, which is now the latest version referenced by the official Google site, so if you bump the version in nDeploy and rebuild, then this should all be fixed.

**Comment by dotsam** [comment] 2016-02-17 18:35
Ah, so the way pagespeed tags/releases work, this isn't actually in the "release" archive, so simply changing the version number won't grab this change, probably not until they push 1.10.33.6 as the release version.

**Comment by AnoopAlias** [comment] 2016-02-18 15:15
Yeah I think it will get pushed in 1.10.33.6 . I will keep an eye on it and update as soon as this is released .

**Comment by AnoopAlias** [comment] 2016-03-04 04:31
Bug was fixed in upstream ngx_pagespeed .

**Closed** 2016-03-04 04:30 UTC
