### ISSUE TITLE
php-fpm failing to start for newly created account

### ISSUE THREAD

**Issue by samapco** [AnoopAlias/nDeploy#23] opened 2015-09-17 20:09 UTC
Hello,

I am receiving an error on a new cpanel account I created. php-fpm is failing to start for that account alone. The php-fpm interface in the cpanel for that account is showing:

Apache PHP-FPM plugin not enabled 
(!) click on the php-fpm icon above to restart the configuration process anytime

This is the php-fpm error log for that account

 [proxy:error] [pid 382647] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/fpmsockets/poconosg.sock (*) failed
[Thu Sep 17 19:38:02.552395 2015] [proxy_fcgi:error] [pid 382647] [client xxx.xxx.xxx.xxx:57043] AH01079: failed to make connection to backend: httpd-UDS, referer: http://domaincreated.com/

**Comment by AnoopAlias** [comment] 2015-09-18 02:19
When a new account is created the watcher.py script fires up 

/opt/nDeploy/scripts/apache_php_config_generator.py USERNAME

Can you manually run the script and paste whatever error you are getting here.

The proxy error you are seeing is because the socket file is not created .So for the root cause you have to see why the socket is not created

**Comment by samapco** [comment] 2015-09-18 08:07
On this page, support.sysally.net/projects/ndeploy/wiki you used this script so that is what I run
/opt/nDeploy/scripts/generate_config.py cpaneluser  but it didn't fix it .

The script you provided in your reply has been able to start it for the account.

But now there are a lot of other issues. apache error_log is showing a lot of proxy_fcgi:errors. 
Yesterday, apache stopped twice and I was receiving 504 Bad gateway errors. when I checked the error log, there were a lot of this error:

 [proxy_fcgi:error] [pid 93401] (32)Broken pipe: [client 172.93.110.34:40815] AH01075: Error dispatching request to : (passing brigade to output filters)

and a lot of this error too:

[core:error] [pid 93945] [client 172.93.110.34:40668] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

**Comment by AnoopAlias** [comment] 2015-09-18 08:23
generate_config.py is for nginx config generation

apache_php_config_generator.py is for apache-php-fpm config generation

Both these are fired up from the watcher.py .If there was no error when you
manually run the script..I doubt watcher script was not running at the time
the account was created ? .


Do you have any SSL websites that has .htaccess redirection to https?. If
yes you need to remove redirect to https from .htaccess and configure https
redirection in nginx ;or since this issue is fixed in the current release
of nDeploy. You just need to upgrade nDeploy.

rm -f /opt/nDeploy/domain-data/*
for CPANELUSER in $(cat /etc/domainusers|cut -d: -f1)
        do
                echo "ConfGen:: $CPANELUSER" &&
/opt/nDeploy/scripts/generate_config.py $CPANELUSER
        done

Which will generate config which doesn't need you to manually remove https
redirection rule in .htaccess


For apache-php-fpm - Troubleshooting involves .

Ensuring the socket file is present in /opt/fpmsockets/USER.sock

If the socket file is there apache should be able to connect to it for php
requests.

#################

Note that issues like "apache stopped twice" has nothing to do with nDeploy
as nDeploy doesnt control apache.It controls only nginx and its config and
php-fpm and its config .

Once you understand how apache works with php-fpm and how php-fpm config
itself works ..it becomes simple


On Fri, Sep 18, 2015 at 1:37 PM, samapco <notifications@github.com> wrote:

> On this page, support.sysally.net/projects/ndeploy/wiki you used this
> script so that is what I run
> /opt/nDeploy/scripts/generate_config.py cpaneluser but it didn't fix it .
>
> The script you provided in your reply has been able to start it for the
> account.
>
> But now there are a lot of other issues. apache error_log is showing a lot
> of proxy_fcgi:errors.
> Yesterday, apache stopped twice and I was receiving 504 Bad gateway
> errors. when I checked the error log, there were a lot of this error:
>
> [proxy_fcgi:error] pid 93401 <http://32>Broken pipe: [client
> 172.93.110.34:40815] AH01075: Error dispatching request to : (passing
> brigade to output filters)
>
> and a lot of this error too:
>
> [core:error] [pid 93945] [client 172.93.110.34:40668] AH00124: Request
> exceeded the limit of 10 internal redirects due to probable configuration
> error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use
> 'LogLevel debug' to get a backtrace.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AnoopAlias/nDeploy/issues/23#issuecomment-141376698>.
>



-- 
Anoop P Alias
PiServe Technologies Pvt Ltd
Phone (office) +91-484-4030077
Phone (mobile)  +91-9846364007
Email - anoop.alias@piserve.com

**Comment by AnoopAlias** [comment] 2015-09-26 07:18
@samapco .

This was indeed a bug.

Please see https://support.sysally.net/news/15

Do
yum --enablerepo=ndeploy install nginx-nDeploy nDeploy

and the error should be fixed.

**Closed by AnoopAlias** 2015-09-26 07:18 UTC
