### ISSUE TITLE
openresty-nDeploy-module-geoip

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#346] opened 2018-05-23 18:34 UTC
Hello,

it looks like openresty-nDeploy-module-geoip (and nginx-nDeploy-module-geoip) was dropped. Is there any chance this can be reenabled?

**Comment by AnoopAlias** [comment] 2018-05-24 01:44
@atxcowboy - Sorry for the fact that the documentation is a bit outdated on this.  geoip module was dropped in favour of the geoip2 module as MaxMind is obsoleting the old (legacy) geoip database 

XtendWebnow include 

```
openresty-nDeploy-module-geoip2
nginx-nDeploy-module-geoip2

```
modules

You will need to 

`yum remove nginx-nDeploy-module-geoip`
and once nginx-nDeploy is updated
`yum install nginx-nDeploy-module-geoip2`

XtendWeb also include a mmdb primer and updater that can be used 

Once geoip2 is installed, run

`/opt/geodns-nDeploy/GeoIP/geoip_update.sh`

You can cron the above command weekly so that the new mmdb database is downloaded weekly

**Comment by AnoopAlias** [comment] 2018-05-24 01:46
@atxcowboy 

If you don't run /opt/geodns-nDeploy/GeoIP/geoip_update.sh after geoip2 installation

nginx config test will error out because the mmdb database will be missing!

**Comment by atxcowboy** [comment] 2018-05-24 06:22
Thanks for the geoip2 hint. However, it looks like I closed this prematurely. I cannot find the script `/opt/geodns-nDeploy/GeoIP/geoip_update.sh `you mentioned and it doesn't seem to be part of the rpms:

```
# rpm -ql openresty-nDeploy-module-geoip2
/etc/nginx/conf.auto/geoip2.conf
/etc/nginx/conf.d
/etc/nginx/fastcgi_params_geoip
/etc/nginx/modules.d/geoip2.load
/etc/nginx/modules.debug.d/geoip2.load
/etc/nginx/modules.debug/ngx_http_geoip2_module.so
/etc/nginx/modules/ngx_http_geoip2_module.so
/usr/nginx/scripts

# rpm -ql libmaxminddb-1.2.0-1.el7.x86_64
/usr/lib64/libmaxminddb.so.0
/usr/lib64/libmaxminddb.so.0.0.7
/usr/share/licenses/libmaxminddb-1.2.0
/usr/share/licenses/libmaxminddb-1.2.0/LICENSE

# rpm -ql libmaxminddb-devel-1.2.0-1.el7.x86_64 
/usr/bin/mmdblookup
/usr/include/maxminddb.h
/usr/include/maxminddb_config.h
/usr/lib64/libmaxminddb.so
/usr/lib64/pkgconfig/libmaxminddb.pc
/usr/share/doc/libmaxminddb-devel-1.2.0
/usr/share/doc/libmaxminddb-devel-1.2.0/Changes.md
/usr/share/licenses/libmaxminddb-devel-1.2.0
/usr/share/licenses/libmaxminddb-devel-1.2.0/NOTICE
/usr/share/man/man1/mmdblookup.1.gz
/usr/share/man/man3/MMDB_aget_value.3.gz
/usr/share/man/man3/MMDB_close.3.gz
/usr/share/man/man3/MMDB_dump_entry_data_list.3.gz
/usr/share/man/man3/MMDB_free_entry_data_list.3.gz
/usr/share/man/man3/MMDB_get_entry_data_list.3.gz
/usr/share/man/man3/MMDB_get_metadata_as_entry_data_list.3.gz
/usr/share/man/man3/MMDB_get_value.3.gz
/usr/share/man/man3/MMDB_lib_version.3.gz
/usr/share/man/man3/MMDB_lookup_sockaddr.3.gz
/usr/share/man/man3/MMDB_lookup_string.3.gz
/usr/share/man/man3/MMDB_open.3.gz
/usr/share/man/man3/MMDB_read_node.3.gz
/usr/share/man/man3/MMDB_strerror.3.gz
/usr/share/man/man3/MMDB_vget_value.3.gz
/usr/share/man/man3/libmaxminddb.3.gz
```

**Comment by atxcowboy** [comment] 2018-05-24 06:38
Ah, the rpm geodns-nDeploy is needed in addition to this and should probably be marked as a dependency. Once I installed it manually, I got the missing parts of the puzzle.

**Comment by AnoopAlias** [comment] 2018-05-24 06:39
@atxcowboy 

Please do

yum --enablerepo=ndeploy install geodns-nDeploy

This rpm is tagged as a dependency in nginx-nDeploy. I might have missed it in openresty 

Would add it in the next release

**Comment by AnoopAlias** [comment] 2018-05-24 06:43
# rpm -qpR nginx-nDeploy-module-geoip2-1.13.12-5.el7.x86_64.rpm
warning: nginx-nDeploy-module-geoip2-1.13.12-5.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 8754ddd7: NOKEY
libmaxminddb
libmaxminddb-devel
nginx-nDeploy
geodns-nDeploy
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
###

# rpm -qpR openresty-nDeploy-module-geoip2-1.13.6.1-13.el7.x86_64.rpm
warning: openresty-nDeploy-module-geoip2-1.13.6.1-13.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 8754ddd7: NOKEY
libmaxminddb
libmaxminddb-devel
openresty-nDeploy
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1


Yes I missed adding the dep. Thanks for getting this to my attention

**Comment by AnoopAlias** [comment] 2018-05-24 11:12
closing as the issue is fixed in build script

**Closed as completed by AnoopAlias** 2018-05-24 11:12 UTC
